# These are supported funding model platforms

pgamerxdev: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
pgamerx: # Replace with a single Patreon username
['https://paypal.me/discordsheep']: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
